<?php $statsHost = 'http://stats.imagevuex.com'; ?>
<div class="narrow">

	<div class="bodyContent single">
		<h1>Authorize your installation</h1>


		<?php if (!in_array('noteAuthorization', ivPool::get('notes'))): ?>
			<div class="note">
				<a id="noteAuthorization" href="#" class="close">&times;</a>
				If you do not have an Imagevue orderID, you will need to purchase a license.
				<a title="About Imagevue Authorization" class="iv-ext" target="_blank" href="http://imagevuex.com/documentation/authorization/">Imagevue Authorization</a>
			</div>
		<?php endif; ?>

		<div id="result" class="pageMessenger">
		</div>

		<form id="authForm" action="<?php echo htmlspecialchars($statsHost); ?>/auth/index.php" method="post" onsubmit="return false;">
			<table class="nice">
				<thead>
					<tr>
						<th colspan="2">
							Please Authorize your Imagevue Installation
							<a class="iv-help" target="_blank" title="What is Authorization?" href="http://imagevuex.com/documentation/authorization/"></a>
						</th>
					</tr>
				</thead>
				<tr>
					<td width="1%">Your&nbsp;Domain</td>
					<td><input type="text" class="text" name="auth[host]" value="<?php echo htmlspecialchars($_SERVER['HTTP_HOST']); ?>" /></td>
				</tr>
				<tr>
					<td width="1%">Order&nbsp;ID</td>
					<td><input type="text" class="text" name="auth[order_id]" /></td>
				</tr>
				<tr>
					<td>Email</td>
					<td><input type="text" class="text" name="auth[email]" /></td>
				</tr>
				<tr class="controls left">
					<td></td>
					<td>
						<input type="submit" class="button buttonSave" value="Send"/>
					</td>
				</tr>
			</table>
		</form>
	</div>

	<script type="text/javascript">
	  $(document).ready(function() {
	    $('#authForm').submit(function () {
	      $.cookie('authCheck', null);
	      $.getJSON('<?php echo $statsHost; ?>/auth/jsonp.php?callback=?', $('#authForm').serialize(), function(json) {
	        $('#result').html('');
	        $.each(json, function (name, value) {
	          if ('status' != name)
	            $('#result')[0].innerHTML += '<div class="' + name + '">' + value + '</div>';
	        });
	      });
	    });
	  });
	</script>
</div>
