<div class="narrow">
	
	<div class="bodyContent single">
		<h1>PHP Information</h1>



		<?php if (!in_array('noteDiag', ivPool::get('notes'))): ?>
			<div class="note">
				<a id="noteDiag" href="#" class="close">&times;</a>
				This page is used to help to diagnose your gallery if something is not working properly.
			</div>
		<?php endif; ?>

		<div class="contentMenu">
			<a href="index.php?c=diag">File System</a>
			<a href="index.php?c=diag&amp;a=errors">PHP check</a>
			<a href="index.php?c=diag&amp;a=apachemod#error">Apache modules check</a>
			<a href="index.php?c=diag&amp;a=phpinfo" class="selected">PhpInfo</a>
		</div>
	</div>
	<div class="phpInfo">
		<iframe src="../iv-includes/phpinfo.php" width="100%" height="20000px" frameborder="0" id="frame"></iframe>
	</div>
</div>
