<div class="narrow">

	<div  class="bodyContent single">
		<h1>User management</h1>

		<?php if (!in_array('noteUsers', ivPool::get('notes'))): ?>
			<div class="note">
				<a id="noteUsers" href="#" class="close">&times;</a>
				You can create multiple users for the Imagevue Control Panel.
				<a title="Imagevue User Management" href="http://imagevuex.com/documentation/settings-page/" class="iv-ext" target="_blank">Users Page</a>
			</div>
		<?php endif; ?>

		<!-- #user -->

		<div class="controls left">
			<a href="?c=user&amp;a=edit" class="button buttonNew">Add user</a>
		</div>

	        <table class="nice">
				<thead>
					<th>User</td>
					<th>Permissions</td>
					<th>&nbsp;</td>
				</thead>

				<?php
					$i = 0;
					$users = $this->users;
					foreach ($users as $user):
						if (ivAcl::isAdmin($user->login)):
							$i++;
						?>

						<tr>
							<td><a title="edit" href="?c=user&amp;a=edit&amp;login=<?php echo urlencode($user->login) ?>"><?php echo ($this->user == $user->login ? '<b>' . htmlspecialchars($user->login) . '<b>' : htmlspecialchars($user->login)); ?></a></td>
								<td></td>
							<td>
								<a  class="button buttonEdit" title="Edit" href="?c=user&amp;a=edit&amp;login=<?php echo urlencode($user->login) ?>">Edit</a>
								<a class="button buttonDelete" title="Delete" href="?c=user&amp;a=delete&amp;login=<?php echo urlencode($user->login) ?>" onclick="return confirm('Are you sure you want to delete user <?php echo htmlspecialchars($user->login); ?>?');">Delete</a>
							</td>
						</tr>

						<?php
						endif;
					endforeach;
					foreach ($users as $user):
						if (!ivAcl::isAdmin($user->login)):
							$i++;
						?>

						<tr class="<?php echo ($i % 2 ? 'odd' : ''); ?>">
							<td><a title="edit" href="?c=user&amp;a=edit&amp;login=<?php echo urlencode($user->login) ?>"><?php echo urlencode($user->login) ?></a></td>
							<td><?php echo htmlspecialchars($user->access); ?></td>
							<td>
								<a  class="button buttonEdit" title="Edit" href="?c=user&amp;a=edit&amp;login=<?php echo urlencode($user->login) ?>">Edit</a>
							<a  class="button buttonDelete" title="Delete" href="?c=user&amp;a=delete&amp;login=<?php echo urlencode($user->login) ?>">Delete</a>
							</td>
						</tr>

						<?php
						endif;
					endforeach;
				?>

				</table>

					<div class="controls left">
						<a href="?c=user&amp;a=edit" class="button buttonNew">Add user</a>
					</div>
	</div>
</div>
